config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :books

  root 'welcome#index'

  get 'books/edit/:id', to: 'books#edit'

  get "books/genre/:genre", to: "books#by_genre"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true,
                  length: { maximum: 50 }
  validates :description, length: {maximum: 300}
  validates :author, presence: true

  def find_by_genre
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret2", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def by_genre
    Book.find_by_genre(params[:genre])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  private
    def book_params
      params.require(:book).permit(:title,:author,:year,:genre,:description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
    <%= form.label :year %><br>
    <%= form.text_field :year %>
  </p>

  <p>
    <%= form.label :genre %><br>
    <%= form.text_field :genre %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/books/by_genre.html.erb
<h1><%= @book.title%></h1>
<h2>Book #<%= @book.id %></h1>

<br>
<p>
<strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Year:</strong>
  <%= @book.year %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<%= link_to 'Add a Book' , new_book_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Genre</th>
    <th>Year</th>
    <th>Description</th>
  </tr>

  <%@books.each do |book|%>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.genre %></td>
      <td><%= book.year %></td>
      <td><%= book.description %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Delete', book_path(book),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h1><%= @book.title%></h1>
<h2>Book #<%= @book.id %></h1>

<br>
<p>
<strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Year:</strong>
  <%= @book.year %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freeshelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Books' , controller: 'books' %>